create table if not exists resume_builder_profiles (tenant_id uuid primary key references users(id) on delete cascade, profile jsonb not null, updated_at timestamptz not null default now());
create table if not exists resume_builder_documents (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references users(id) on delete cascade, title text not null, revision integer not null default 1 check(revision>0), job_id uuid references jobs(id) on delete set null, profile jsonb not null, design jsonb not null, updated_at timestamptz not null default now(), unique(tenant_id,id));
create table if not exists resume_builder_proposals (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references users(id) on delete cascade, document_id uuid not null, revision integer not null, target text not null, before_text text not null, after_text text not null, reason text not null, status text not null default 'pending' check(status in ('pending','accepted','rejected','stale','blocked')), render_status text not null default 'idle' check(render_status in ('idle','running','passed','failed')), render_error text, foreign key(tenant_id,document_id) references resume_builder_documents(tenant_id,id) on delete cascade);
create table if not exists resume_builder_versions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references users(id) on delete cascade, document_id uuid not null, title text not null, snapshot jsonb not null, pdf bytea not null, created_at timestamptz not null default now(), expires_at timestamptz not null default (now()+interval '60 days'), foreign key(tenant_id,document_id) references resume_builder_documents(tenant_id,id) on delete cascade);
alter table resume_builder_profiles enable row level security;
alter table resume_builder_profiles force row level security;
drop policy if exists tenant_isolation on resume_builder_profiles;
create policy tenant_isolation on resume_builder_profiles using (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid) with check (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid);
grant select,insert,delete,update on resume_builder_profiles to app_rw;
alter table resume_builder_documents enable row level security;
alter table resume_builder_documents force row level security;
drop policy if exists tenant_isolation on resume_builder_documents;
create policy tenant_isolation on resume_builder_documents using (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid) with check (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid);
grant select,insert,delete,update on resume_builder_documents to app_rw;
alter table resume_builder_proposals enable row level security;
alter table resume_builder_proposals force row level security;
drop policy if exists tenant_isolation on resume_builder_proposals;
create policy tenant_isolation on resume_builder_proposals using (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid) with check (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid);
grant select,insert,delete,update on resume_builder_proposals to app_rw;
alter table resume_builder_versions enable row level security;
alter table resume_builder_versions force row level security;
drop policy if exists tenant_isolation on resume_builder_versions;
create policy tenant_isolation on resume_builder_versions using (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid) with check (tenant_id = nullif(current_setting('app.tenant_id',true),'')::uuid);
grant select,insert,delete on resume_builder_versions to app_rw;
create index if not exists resume_builder_documents_tenant on resume_builder_documents(tenant_id,updated_at);
-- Earlier default privileges grant UPDATE on new tables. Explicitly remove it.
revoke update on resume_builder_versions from app_rw;
create index if not exists resume_builder_proposals_doc on resume_builder_proposals(tenant_id,document_id);
create index if not exists resume_builder_versions_doc on resume_builder_versions(tenant_id,document_id,expires_at);
