import type { BuilderProfile, BuilderDesign } from './resume-builder-model';
import { BUILDER_FONTS } from './resume-builder-font-assets';
const escape = (s: string) => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
// Version 1 is immutable: add a new template version rather than editing existing saved designs.
const paginate = `(async()=>{try{
await Promise.all([document.fonts.load('400 11pt ResumeFont'),document.fonts.load('700 11pt ResumeFont')]);await document.fonts.ready;
if(!document.fonts.check('400 11pt ResumeFont')||!document.fonts.check('700 11pt ResumeFont'))throw Error('Resume font failed to load. Retry rendering.');
const source=document.querySelector('#source'), blocks=[...source.children], expected=blocks.length, pages=document.querySelector('#pages');let page,flow;
function fresh(){page=document.createElement('article');page.className='page';page.innerHTML=document.querySelector('#shell').innerHTML;pages.append(page);flow=page.querySelector('.flow');if(pages.children.length>1){page.classList.add('continuation');page.querySelector('.identity').textContent=document.querySelector('#identity-name').textContent+' · continued';page.querySelectorAll('.first-only').forEach(e=>e.remove());}return flow;}
fresh();
for(const block of blocks){flow.append(block);if(flow.scrollHeight>flow.clientHeight+1){block.remove();if(!flow.children.length)throw Error('A content block cannot fit on one page. Shorten that paragraph or bullet.');fresh();flow.append(block);if(flow.scrollHeight>flow.clientHeight+1)throw Error('A content block cannot fit on one page. Shorten that paragraph or bullet.');}if(pages.children.length>20)throw Error('Resume exceeds the supported page count. Shorten the content.');}
source.remove();
if(document.querySelectorAll('.flow > .block').length!==expected)throw Error('Resume content validation failed. Retry rendering.');
for(const p of pages.children){for(const container of p.querySelectorAll('.flow,.rail,.identity')){const bound=container.getBoundingClientRect();if(container.scrollHeight>container.clientHeight+1||container.scrollWidth>container.clientWidth+1)throw Error('Content does not fit its page area. Shorten the text.');for(const el of container.querySelectorAll('[data-text]')){const range=document.createRange();range.selectNodeContents(el);for(const r of range.getClientRects()){if(r.left<bound.left-1||r.right>bound.right+1||r.top<bound.top-1||r.bottom>bound.bottom+1)throw Error('Text would be clipped. Shorten the content or change the template.');}}}let bottom=0;for(const b of p.querySelectorAll('.flow > .block')){const r=b.getBoundingClientRect();if(r.top<bottom-0.5)throw Error('Resume blocks overlap. Retry rendering.');bottom=r.bottom;}}
window.__resumeRender={pageCount:pages.children.length,blocks:expected};
}catch(e){window.__resumeRender={error:e.message};const notice=document.createElement('p');notice.textContent=e.message;notice.setAttribute('role','alert');document.body.prepend(notice);}})();`;
export function builderHtml(profile: BuilderProfile, design: BuilderDesign): string {
 if(design.templateVersion && design.templateVersion!=='1')throw new Error('Unsupported resume template version. Restore a supported version.');
 if(!['classic','editorial','sidebar'].includes(design.template)||!['letter','a4'].includes(design.pageSize)||![1,2].includes(design.pageLimit)||!['sans','serif'].includes(design.font)||!['slate','blue','green'].includes(design.accent))throw new Error('Unsupported resume design. Choose a supported template and paper size.');
 const txt=(tag:string,text:string,cls='')=>text?`<${tag} class="${cls}" data-text>${escape(text)}</${tag}>`:'';
 const block=(html:string)=>`<div class="block">${html}</div>`;
 const entries=profile.sections.flatMap(s=>s.entries.map((e,i)=>{
 const first=(i===0?txt('h2',s.title):'')+txt('h3',e.heading)+txt('p',e.subheading,'subheading')+txt('p',e.dates,'dates')+(e.bullets[0]?txt('p',e.bullets[0].text,'bullet'):'');
 return block(first)+e.bullets.slice(1).map(b=>block(txt('p',b.text,'bullet'))).join('');
 })).join('');
 const sidebar=design.template==='sidebar';
 const rail=sidebar?`<aside class="rail">${txt('p',profile.contact,'contact first-only')}${txt('p',profile.summary,'summary first-only')}</aside>`:'';
 const header=`<header class="identity"><span id="identity-name" data-text>${escape(profile.name)}</span>${txt('p',profile.headline,'headline first-only')}${!sidebar?txt('p',profile.contact,'contact first-only'):''}</header>`;
 const width=design.pageSize==='a4'?'210mm':'8.5in',height=design.pageSize==='a4'?'297mm':'11in';
 const accent={slate:'#334155',blue:'#1e466d',green:'#285347'}[design.accent];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:; script-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; base-uri 'none'; form-action 'none'"><style>
 @font-face{font-family:ResumeFont;src:url(data:font/ttf;base64,${BUILDER_FONTS[design.font]}) format('truetype');font-weight:100 900;font-style:normal;font-display:block}
 @page{size:${width} ${height};margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0}body{background:#e5e7eb;color:#17202a;font-family:ResumeFont;font-size:10.5pt;line-height:1.38;font-synthesis:none}.page{width:${width};height:${height};padding:.55in;background:white;display:flex;flex-direction:column;break-after:page;page-break-after:always;margin:0 auto 16px}.page:last-child{break-after:auto;page-break-after:auto}.identity{flex:none;font-size:25pt;font-weight:700;color:${accent};overflow-wrap:anywhere;padding-bottom:14px}.identity p{font-weight:400}.headline{font-size:12pt;margin:4px 0}.contact{font-size:9pt;margin:4px 0}.layout{display:flex;gap:24px;flex:1;min-height:0}.flow{flex:1;min-width:0;display:flex;flex-direction:column}.block{flex:none;padding-bottom:7px;overflow-wrap:anywhere}p{margin:0;white-space:pre-wrap}h2{font-size:12pt;letter-spacing:.06em;margin:8px 0 7px;border-bottom:1px solid ${accent};color:${accent};padding-bottom:4px}h3{font-size:11pt;margin:0}.subheading{font-size:10pt}.dates{font-size:9pt;color:#475569;margin-bottom:5px}.bullet{padding-left:12px;position:relative}.bullet:before{content:'•';position:absolute;left:0}.summary{margin-bottom:12px}.rail{width:1.65in;flex:none;background:#eff3f5;padding:12px;overflow-wrap:anywhere}.continuation .identity{font-size:12pt;padding-bottom:12px}.continuation .rail{background:#eff3f5;border-top:3px solid ${accent}}[data-template=editorial] .identity{font-size:34pt;text-align:center;border-top:5px solid ${accent};padding-top:14px;margin-bottom:14px}[data-template=editorial] h2{font-size:14pt;letter-spacing:0;border:0;border-left:3px solid ${accent};padding-left:10px}[data-template=editorial] .block{padding-bottom:10px}[data-template=sidebar] .identity{border-bottom:3px solid ${accent};margin-bottom:15px}[data-template=sidebar] h2{font-size:11pt}#source{position:absolute;visibility:hidden;width:6in}@media print{body{background:white}.page{margin:0}}
 </style></head><body data-template="${design.template}" data-version="1"><template id="shell">${header}<div class="layout">${rail}<main class="flow"></main></div></template><div id="pages"></div><div id="source">${!sidebar&&profile.summary?block(txt('p',profile.summary,'summary')):''}${entries}</div><script>${paginate}</script></body></html>`;
}
