#!/bin/sh
# Proves a backup can actually be RESTORED. Run it after any change to
# db/backup.mjs, and periodically regardless.
#
# An untested backup is a hypothesis. A dump that parses, uploads, and reports
# success can still restore into nothing — wrong database, partial schema,
# truncated stream. The only evidence that matters is a restore whose row counts
# match the source.
#
# Restores into a SCRATCH database, never the live one, and the drop at the end
# is guarded on the scratch name prefix so it cannot target `railway` even if
# edited carelessly.
#
#   railway run --service Postgres sh db/restore-verify.sh
#
# Uses the TCP proxy vars because the private host does not resolve off-platform;
# inside a Railway container PGHOST/PGPORT work directly.
set -e

SCRATCH="restore_verify_scratch"
HOST="${RAILWAY_TCP_PROXY_DOMAIN:-$PGHOST}"
PORT="${RAILWAY_TCP_PROXY_PORT:-$PGPORT}"
export PGPASSWORD

COUNTS="select current_database() || ' | jobs=' || (select count(*) from jobs) \
  || ' watchlist=' || (select count(*) from watchlist) \
  || ' settings=' || (select count(*) from app_settings)"

echo "== source =="
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d railway -tAc "$COUNTS"

echo "== dumping =="
pg_dump -h "$HOST" -p "$PORT" -U "$PGUSER" -d railway --no-owner --no-acl -f /tmp/verify.sql
echo "dump bytes: $(wc -c < /tmp/verify.sql)"

echo "== creating scratch db =="
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d railway -c "drop database if exists $SCRATCH" >/dev/null
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d railway -c "create database $SCRATCH" >/dev/null

echo "== restoring =="
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d "$SCRATCH" -q -f /tmp/verify.sql >/dev/null 2>&1

echo "== restored (row counts MUST match the source above) =="
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d "$SCRATCH" -tAc "$COUNTS"

# The fit brain is the single most valuable row in this database — months of
# iteration, and the only thing here that cannot be regenerated by re-running a
# search. Check it explicitly rather than trusting an aggregate count.
echo "== spot-check: the fit brain survived =="
psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d "$SCRATCH" -tAc \
  "select 'fitBrain chars=' || length(value::text) from app_settings where key='fitBrain'"

echo "== dropping scratch (guarded) =="
case "$SCRATCH" in
  restore_verify_*) psql -h "$HOST" -p "$PORT" -U "$PGUSER" -d railway -c "drop database $SCRATCH" >/dev/null && echo "dropped $SCRATCH" ;;
  *) echo "REFUSED to drop '$SCRATCH' — name does not match the scratch prefix"; exit 1 ;;
esac
rm -f /tmp/verify.sql
